// Souris — Appointment item snapshot
//
// Source: docs/domain/APPOINTMENTS.md §12–§13
//
// An AppointmentItem is a historical snapshot of a catalog Service at
// booking time. Later catalog changes (price, name, phases, type) must
// never silently change existing appointments.

import type { AppointmentItem, Service } from "./types";

export interface CreateAppointmentItemSnapshotInput {
  /**
   * Identifier of the new AppointmentItem.
   * Generated by the caller — this domain function never invents ids.
   */
  readonly id: string;
  readonly service: Service;
  readonly order: number;
  readonly serviceOptionId?: string;
}

/**
 * Creates an immutable AppointmentItem snapshot from a catalog Service.
 *
 * Phase data is copied into new objects, so the snapshot holds no reference
 * to catalog structures and remains unchanged if the Service later evolves.
 */
export function createAppointmentItemSnapshot(
  input: CreateAppointmentItemSnapshotInput,
): AppointmentItem {
  const { id, service, order, serviceOptionId } = input;

  return {
    id,
    serviceId: service.id,
    serviceOptionId,
    order,
    serviceName: service.name,
    serviceType: service.type,
    price: service.price,
    phases: service.phases.map((phase) => ({
      id: phase.id,
      name: phase.name,
      durationMinutes: phase.durationMinutes,
      requiresStaff: phase.requiresStaff,
    })),
  };
}
