// Souris — Sale domain rules
//
// Pure helpers over the canonical Sale model: quantity validation, derived
// totals, and the SaleItem snapshot boundary. Nothing here mutates its input.

import type { SaleItem } from './types';

/** Sale quantities are whole units, at least one. */
export function isValidSaleQuantity(quantity: number): boolean {
  return Number.isInteger(quantity) && quantity >= 1;
}

/** Derived line total — never stored. */
export function getSaleItemTotal(item: Pick<SaleItem, 'unitPrice' | 'quantity'>): number {
  return item.unitPrice * item.quantity;
}

/** Derived Sale total — never stored. Accepts any priced/quantified lines. */
export function getSaleTotal(sale: {
  readonly items: readonly Pick<SaleItem, 'unitPrice' | 'quantity'>[];
}): number {
  return sale.items.reduce((total, item) => total + getSaleItemTotal(item), 0);
}

/** Total number of units across every line. */
export function getSaleUnitCount(sale: {
  readonly items: readonly Pick<SaleItem, 'quantity'>[];
}): number {
  return sale.items.reduce((count, item) => count + item.quantity, 0);
}

/** The Product fields a SaleItem snapshots. Image is deliberately excluded. */
export interface SaleItemSnapshotSource {
  readonly id: string;
  readonly name: string;
  readonly price: number;
}

export interface CreateSaleItemSnapshotInput {
  /** Identifier of the new SaleItem — generated by the caller, never here. */
  readonly id: string;
  readonly product: SaleItemSnapshotSource;
  readonly quantity: number;
}

/**
 * Creates an immutable SaleItem snapshot from the current Product values.
 * The Product object is never referenced afterwards: later catalog edits or
 * deletion cannot reach the historical line.
 */
export function createSaleItemSnapshot(input: CreateSaleItemSnapshotInput): SaleItem {
  const { id, product, quantity } = input;
  if (!isValidSaleQuantity(quantity)) {
    throw new RangeError(`createSaleItemSnapshot: invalid quantity ${quantity}`);
  }

  return {
    id,
    productId: product.id,
    productName: product.name,
    unitPrice: product.price,
    quantity,
  };
}
